name: Bug report
description: Report a bug to help improve the project
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: |
        Use this bug report template to report issues with the project

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please make sure to search in the [issues](https://github.com/ko4life-net/ko/issues) first to see
        whether the same issue was reported already.
      options:
        - label: >
            I searched the [issues](https://github.com/ko4life-net/ko/issues) and found
            no similar issues.
          required: true

  - type: textarea
    attributes:
      label: Description
      description: Describe what happened.
      placeholder: >
        Please provide the context in which the problem occurred and explain what happened.
        We also encourage you to attach pictures or files of the problem, such as errors, log files and vice versa.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behaviour
      description: What is your expected behaviour
      placeholder: Please explain what behaviour you expected.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Observed Behaviour
      description: What is your observed behaviour
      placeholder: >
        Please explain what you observed, and why you think the behaviour is erroneous. It is extremely
        helpful if you include any output and logging output with exact error messages, stack traces, etc.
    validations:
      required: true

  - type: textarea
    attributes:
      label: How to reproduce
      description: >
        What should we do to reproduce the problem?
      placeholder: >
        Please make sure you provide a reproducible step-by-step case of how to reproduce as minimally and precisely as possible.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Are you willing to work on and submit a PR to address the issue?
      description: >
        This is absolutely not required, but we are happy to guide you in the contribution process,
        especially if you already have a good understanding of how to implement the fix.
        The project is a totally community-driven and we love to bring new contributors in.
      options:
        - label: Yes I am willing to submit a PR!

  - type: markdown
    attributes:
      value: "Thanks for completing our form!"
