name: Documentation Issue
description: Report an issue or a suggestion with our documentation to help improve the project
labels: [ "documentation" ]
body:
  - type: markdown
    attributes:
      value: |
        Use this documentation template to report issues with documentation.

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please make sure to search in the [issues](https://github.com/ko4life-net/ko/issues) first to see
        whether the same issue was reported already.
      options:
        - label: >
            I searched the [issues](https://github.com/ko4life-net/ko/issues) and found
            no similar issues.
          required: true

  - type: textarea
    attributes:
      label: Issue/Suggested Improvement
      description: The issue you found or the improvement you suggest.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Are you willing to work on and submit a PR to address the issue?
      description: >
        This is absolutely not required, but we are happy to guide you in the contribution process,
        especially if you already have a good understanding of how to implement the fix.
        The project is a totally community-driven and we love to bring new contributors in.
      options:
        - label: Yes I am willing to submit a PR!

  - type: markdown
    attributes:
      value: "Thanks for completing our form!"
