name: Build Game and Server
on: [workflow_dispatch]

jobs:
  Windows:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        shell: cmd
        run: |
          git submodule init src/vendor
          git submodule update src/vendor

      - name: Build KnightOnLine
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
          cd src
          msbuild Game.sln -t:Clean -t:Build -p:Configuration=Release /m

      - name: Build Server
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
          cd src
          msbuild Server.sln -t:Clean -t:Build -p:Configuration=Release /m

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: x86-release
          path: src/build/x86-Release/*.exe
