name: Build All
on: [workflow_dispatch]

jobs:
  Windows:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        shell: cmd
        run: |
          git submodule init src/vendor
          git submodule update src/vendor

      - name: Build All - Debug
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
          cd src
          msbuild All.sln -t:Clean -t:Build -p:Configuration=Debug /m

      - name: Build All - Release
        shell: cmd
        run: |
          git reset --hard
          git clean -xffd
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
          cd src
          msbuild All.sln -t:Clean -t:Build -p:Configuration=Release /m

      - name: Upload - Release
        uses: actions/upload-artifact@v4
        with:
          name: All-x86-release
          path: src/build/x86-Release/*.exe
